### ISSUE TITLE
Issues with protocol relative links

### ISSUE THREAD

**Issue by khromov** [voceconnect/cdn-rewrite#5]
There seems to be some issues with protocol relative links.

In WooCommerce, some scripts (like add-to-cart.min.js) are enqueued using a protocol relative url ( // )

These links are not properly rewritten by WP CDN Rewrite, they remain at their old URL:s.

To replicate, just install WooCommerce and check any page while WP CDN Rewrite is enabled.

**Comment by khromov** [comment]
@csloisel @petevoce @smccafferty @tiburon @tylercherpak Any fix for this? I see there's a PR ready in #6

**Comment by tylercherpak** [comment]
Hello @khromov I have updated the plugin. Let us know if you have any other issue. Thanks!
